### ISSUE TITLE
Add category for SCM

### ISSUE THREAD

**Issue by caniszczyk** [cdfoundation/cdf-landscape#16]
There should be a category for SCM systems for CI/CD

We used to have one in the CNCF landscape but decided that was out of scope, I think it's in perfect scope for CDF... see this post for an older picture: https://medium.com/memory-leak/cloud-native-landscape-celebrates-first-anniversary-69a4eb829505

**Comment by TracyRagan** [comment]
Of course!   I will add it.

**Comment by TracyRagan** [comment]
Ok  - it is added and up there.

**Comment by sbtaylor15** [comment]
See PR #32

**Comment by danlopez00** [comment]
merged
