### ISSUE TITLE
Cloud Native should NOT be a category

### ISSUE THREAD

**Issue by kostis-codefresh** [cdfoundation/cdf-landscape#181]
Cloud native is a characteristic/trait. It doesn't make sense to have a category, because then 90% of the other cards should also be here. 

It also gives the false impression that tools that are not there are "not" cloud native.

Isn't Tekton cloud native?
Isn't ArgoCD cloud native?
Isn't Shipwright cloud native?

The current contents of this "category" are unrelated. Terraform is a CLI that implements infrastructure as code, Rancher is a cluster orchestration/management platform, Alibaba is a whole cloud provider, while Ketch is an application for Kubernetes deployments.

Related to https://github.com/cdfoundation/cdf-landscape/issues/175

**Comment by sbtaylor15** [comment]
Point to the CNCF landscape as a embedded landscape link. This will enable us to have the CNCF maintain the landscape for this category.

**Comment by MarckK** [comment]
Make all one Infrastructure Deployments -- remove subcategories.

**Comment by MarckK** [comment]
Closing as remaining work to be done is surfaced in #208.
