### ISSUE TITLE
Puppet under Infrastructure category instead of Config Management category

### ISSUE THREAD

**Issue by obowersa** [cdfoundation/cdf-landscape#185]
Raising this as an issue, despite the guidelines, as I'm waiting to hear back from puppet on if the current category was a deliberate choice. Once I've heard back I'll open a PR if required.  Wanted to make sure this was visible in case anyone else has the same query.

Puppet generally is viewed as a tool in the same space as Chef/Saltstack/Ansible/etc. As we have a category for those tools, I /think/ puppet should sit under there.

**Comment by MarckK** [comment]
#175

**Comment by MarckK** [comment]
closed by #204
