### ISSUE TITLE
Fix OpenMake logo

### ISSUE THREAD

**Issue by danlopez00** [cdfoundation/cdf-landscape#19]
OpenMake logo needs to be SVG in cached_logos and hosted_logos

https://www.openmakesoftware.com/

**Comment by sbtaylor15** [comment]
@danlopez00 - The correct svg is in the hosted_logos directory.  I think the cached_logos needs to be cleaned up prior to running the `npm run build` since the build copies files from various locations into the cached_logos directory.

cc: @TracyRagan

**Comment by dankohn** [comment]
You don’t need to do anything with the cached folder. The build automatically adds or deleted based on what is referred to from landscape.yml.

**Comment by sbtaylor15** [comment]
@dankohn - has the latest cached folder been push back to the repo so I can verify the openmake logo?  There is a difference between the hosted and cached logos.

**Comment by dankohn** [comment]
Cached is rebuilt as part of the deployment process. If you want to install locally you can do the same thing by running yf but there’s no need.

**Comment by sbtaylor15** [comment]
@dankohn then why is the openmake logo incorrect on the website if its correct in the hosted_logos directory?

**Comment by dankohn** [comment]
I fixed manually. However, please note that the OpenMake logo is not of sufficient quality. You can't convert a PNG to be an SVG. Instead, you should ask @alexcontini to recreate the logo.

**Comment by dankohn** [comment]
Also note that logos need to have a transparent background.
