### ISSUE TITLE
Continuous Quality

### ISSUE THREAD

**Issue by eobianwu** [cdfoundation/cdf-landscape#193]
I know real estate is limited on the landscape, but the multitude of testing workloads across the lifecycle (shift left, shift right, release testing) could warrant a dedicated box for testing perhaps called "Continuous Quality". Allows for painting a broader (but connected) picture of testing across the lifecycle. Unit testing through post deployment testing.

**Comment by MarckK** [comment]
#175

**Comment by tracymiranda** [comment]
+1 and this could include subcategories for Automated, Manual.

Load testing, continuous testing wording. 

What are the additional tools in this space?
- Appium
- Launchable
-

**Comment by tracymiranda** [comment]
@eobianwu can you add additional suggestions

**Comment by TracyRagan** [comment]
@eobianwu @MarckK Here is a spreadsheet that I worked on with the outreach team for prospective members back in March/April. At the time I focused on continuous test so there are several companies listed there. I did not break out the testing group for Landscape purposes but I believe it is a good start on the companies in this broader category.  
 https://docs.google.com/spreadsheets/d/1IJQisvTs8DQ5CzdvF3wMdRFdTqeXy83k5VXLP5Jd2ag/edit?usp=sharing

**Comment by eobianwu** [comment]
@tracymiranda @MarckK I propose the following. "Continuous Quality" is the standalone category with the following tools/products/services listed as illustrative of the breadth of testing categories across CD stakeholders (shift left, shift right, and categories of testing) JUnit, JMeter, Browserstack, Appium, Selenium, Testlio, LaunchDarkly, Netsparker.
