### ISSUE TITLE
Measuring and Reporting Category

### ISSUE THREAD

**Issue by MarckK** [cdfoundation/cdf-landscape#195]
### Category request:

Brought up by @tracymiranda and @sbtaylor15 at landscape wg meeting.

To cover reporting and dashboards, etc. 

potential projects
[Four Keys Project](https://github.com/GoogleCloudPlatform/fourkeys)
Open Telementry -- potential category of Observability
Daily Motion's Dora metrics project
[Hygieia](https://www.capitalone.com/tech/solutions/hygieia/)- end to end monitoring

**Comment by MarckK** [comment]
Note difference in metrics/ focus between Dora/4 Keys and Dynatrace.

Open Telementry -- operating and feedback.

**Comment by sbtaylor15** [comment]
Split into 2 buckets:
- Pipeline Measuring and Reporting
  - Daily Motion's and Pipeline health
- Observability and Feedback Loop
  - Open Telemetry
  - Dynatrace

**Comment by e-backmark-ericsson** [comment]
I'm thinking of how this relates to the current "Protocols and Messaging" category, which I believe Steve suggests to rename to "Events" according to #200 . If you feel there are too many categories, maybe these two should be merged? I think that both Eiffel and the coming "CD Events" could fit in the same subcategory as Open Telemetry in such a joint category, if we don't want to have too many sub categories either.

**Comment by MarckK** [comment]
Thank you for your feedback and suggestions, @e-backmark-ericsson!

These changes are being prototyped on #203 and currently look like:

<img width="600" alt="Screenshot 2021-11-19 at 22 25 16" src="https://user-images.githubusercontent.com/15032115/142713075-5a2e61c2-a17d-47d7-9047-6e6fe639e087.png">

(DevOps Metrics is for the [4 Keys project](https://github.com/GoogleCloudPlatform/fourkeys) -- I just needed an svg for the prototype)

If we were to group the Tracing and Messaging categories together, along with cdEvents, what would be a good name for this category? 
And would Dynatrace belong with this grouping?

How else would you group the categories shown above? 
I already think Monitoring & Logging should be one category.

**Comment by e-backmark-ericsson** [comment]
I think it would make sense to group them and the category could probably be called "Tracing and Messaging". I don't see any other place in the current landscape layout where the messaging category fits better. Eiffel has an eco-system of tools surrounding the protocol, but they all relate the "messaging" term I would say. Similarly CD Events will probably also provide an eco-system of tools around its protocol, which will ease the use of the coming event protocol.

I don't know too much about the Dynatrace offering, but it seems to be a much broader solution and it would probably be too limiting or even wrong to place it within "Tracing and Messaging".

**Comment by MarckK** [comment]
With @e-backmark-ericsson's  feedback taken on board, the section now looks like:
<img width="461" alt="Screenshot 2021-11-26 at 16 23 17" src="https://user-images.githubusercontent.com/15032115/143655993-3355b6c7-5889-461d-aa31-f599a578eaeb.png">

This is still a prototype for the section and **any and all feedback is welcome!**

**Comment by MarckK** [comment]
Closing this issue as the proposed section above was merged some time ago and is on the landscape.
