### ISSUE TITLE
Fix overlapping text on info box

### ISSUE THREAD

**Issue by tracymiranda** [cdfoundation/cdf-landscape#196]
The text is overlapping here, and google search console informed me about it

![image](https://user-images.githubusercontent.com/5173122/141501368-6edc9653-3d79-4655-b04b-6e7fd7cd0999.png)

### Bug report or Feature or Category request:

Please replace this line with a brief summary of your issue.

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

**Comment by MarckK** [comment]
Closed by #206
