### ISSUE TITLE
Policy Category

### ISSUE THREAD

**Issue by sbtaylor15** [cdfoundation/cdf-landscape#199]
Handle policy management tools that fit into the pipeline.

**Comment by MarckK** [comment]
Hi @sbtaylor15, 

 @idanshahar has suggested adding a Governance sub-category on 257:
 
  
<img width="1229" alt="Screenshot 2022-09-01 at 11 55 33" src="https://user-images.githubusercontent.com/15032115/187960222-fef2ef67-d536-4634-a5e7-7c3f5c772ac9.png">

It would be great to have your input and that of @justinabrahms, @bradmccoydev, and others thinking about policy + pipelines.

**Comment by justinabrahms** [comment]
Policy is a very large space. There's nothing pipeline specific about most of the tools that I know (though I've just learned about Allero). I'll cross post it to the supply chain sig.

**Comment by idanshahar** [comment]
Hey @justinabrahms, here are several pipeline-specific policy tools. However, most of them focus on security practices and are not open source.
[OX Security
](https://www.ox.security/?gclid=Cj0KCQjw08aYBhDlARIsAA_gb0dGRaWRH7KiNqdcY8ilK-Kv_RbNaHZhnndgLSHhNGx9TaaBwj_r8x8aAjh1EALw_wcB)
[Argon Security
](https://www.argon.io/solutions/)
[Spectral Ops
](https://spectralops.io/)
[Apolicy](https://apolicy.io/)

I believe we will see more policy solutions for pipelines getting out there, many companies already developed internal tooling to enforce CI/CD best practices and to support shifting left DevOps.

**Comment by MarckK** [comment]
We now have a subcategory for Policy under the main DevSecOps category on the landscape. 
Please do iterate on this Policy category, with any changes you think are due, including new additions to that category. 
Thank you!

<img width="1255" alt="Screenshot 2022-09-19 at 11 24 47" src="https://user-images.githubusercontent.com/15032115/191054395-ac165231-1411-488f-aad1-ddc87d358752.png">

**Comment by fdegir** [comment]
Kyverno and OPA are now included on the landscape, under policy category as well so closing this issue.

Please either directly add new projects to the category via PRs or open a new issue for changes to existing category and projects.
