### ISSUE TITLE
Events Category

### ISSUE THREAD

**Issue by sbtaylor15** [cdfoundation/cdf-landscape#200]
Event driven projects and tools, ie CDEvents

**Comment by e-backmark-ericsson** [comment]
This would be the current "Protocols and Messaging" category. Maybe it should be renamed? Or merged with the proposed "Measuring and Reporting" category as proposed in #195

**Comment by MarckK** [comment]
Hi @sbtaylor15, further to Emil's comment, please see #195 and comment further there or on #203, which is the prototype for the section.

Closing in favour of #195.
