### ISSUE TITLE
Move Members onto a separate tab (like the CNCF)

### ISSUE THREAD

**Issue by sbtaylor15** [cdfoundation/cdf-landscape#205]
We should follow the CNCF member layout to get more space on the landscape.

![CNCF Cloud Native Interactive Landscape 2021-11-15 11-14-43](https://user-images.githubusercontent.com/14826572/141833791-54af9c3e-3661-4c89-be62-f0ea5d3c833f.png)

![Members - CNCF Cloud Native Interactive Landscape 2021-11-15 11-15-48](https://user-images.githubusercontent.com/14826572/141833806-5dc81965-4290-4913-bc56-ade9694a9416.png)

**Comment by tracymiranda** [comment]
While a members tab has some nice benefits, we are far from the stage where we need more space in the landscape (lots of room to expand wider) and not to mention the landscape is a member benefit and encourages our members to share the landscape with their communities.
