### ISSUE TITLE
Copy paste miss?

### ISSUE THREAD

**Issue by tequilarista** [cdfoundation/cdf-landscape#36]
Looks like this was snagged from the Deep Learning Foundation and missed on fixup:

"This landscape is intended as a map to explore open source artificial intelligence (AI), machine learning (ML), and deep learning (DL) projects, and also shows the member companies of the LF Deep Learning Foundation. "

**Comment by danlopez00** [comment]
Indeed it is!

**Comment by danlopez00** [comment]
fixed
