### ISSUE TITLE
Can you adjust the Logos for all vendor to appear in bottom row in the pipeline/orchestration box

### ISSUE THREAD

**Issue by balajisiva** [cdfoundation/cdf-landscape#39]
### Don't create an issue

If you see an error in the cards or missing ones, please don't create an issue here. Instead, edit landscape.yml (you can even do it via the GitHub web interface) and open a pull request. Then, review the preview staging server that's posted to your pull request and add a comment if your new or updated card looks correct and is ready to merge. Before going forward, please carefully review the sections of the Readme covering new entries, corrections, and logos: https://github.com/cncf/landscape/blob/master/README.md.

**Comment by dankohn** [comment]
No. You can adjust the layout by increasing or decreasing the width of the box but the layout in the box is automated.

**Comment by danlopez00** [comment]
Closing, as this is not possible since it is automated by the code
