### ISSUE TITLE
Incorrect CII badge referenced for Jenkins X project

### ISSUE THREAD

**Issue by MarckK** [cdfoundation/cdf-landscape#54]
For the Jenkins X card, the incorrect CII badge is being referenced.

In the processed_landscape.yml, the incorrect badge is referenced here: https://github.com/cdfoundation/cdf-landscape/blob/master/processed_landscape.yml#L257

The correct CII badge for Jenkins X is 3237: https://bestpractices.coreinfrastructure.org/en/projects/3237

We would appreciate it if this could be updated.
Thank you.

**Comment by dankohn** [comment]
Fixed with #56
