### ISSUE TITLE
Question about valid projects

### ISSUE THREAD

**Issue by obowersa** [cdfoundation/cdf-landscape#67]
Hey all,

Was looking to do some updates to the cdf-landscape and wanted to clarify one of the lines in the README:

'Projects must be open source and hosted on or mirrored to GitHub.'

Is this accurate for new entries ? I noticed there's a few closed source projects on the landscape and wanted to clarify ahead of time.

**Comment by tequilarista** [comment]
Ack, yes I think that's still a requirement we want to hold to, so will need to go back and have a look.  Thanks for the poke.

**Comment by obowersa** [comment]
Thanks for the clarification @tequilarista , I'll close this off
