### ISSUE TITLE
Clarification around Crunchbase as a requirement for submission

### ISSUE THREAD

**Issue by obowersa** [cdfoundation/cdf-landscape#88]
Ref: #84 

## Summary 
Looking for clarification and potential documentation update around handling of projects which don't have a presence on crunchbase

## Description
Request made to add MobSF ( https://github.com/MobSF/Mobile-Security-Framework-MobSF)  to the CDF Landscape. The company which created the tool ( https://opensecurity.in/ ) don't have a presence on crunchbase.

I imagine this is something which has been encountered with the CNCF Landscape so any experience from that would be great. It would be useful to understand if Crunchbase is a hard requirement. I'm uncertain as to how widely adopted crunchbase is internationally.

**Comment by dankohn** [comment]
Anyone can create a missing Crunchbase entry. Just create a free account there.

**Comment by obowersa** [comment]
Oh cool, thanks @dankohn , I had no idea.
